SET SERVEROUTPUT ON DECLARE
CURSOR GET_DATE IS
SELECT * FROM Customs
WHERE id_producta = 2;
a	GET_DATE%ROWTYPE;
BEGIN
OPEN GET_DATE; LOOP
DBMS_OUTPUT.enable;
DBMS_OUTPUT.put_line('Заказы с id=2: '||a.custom_date||' '||a.done_or_not);
FETCH GET_DATE INTO a; 
EXIT WHEN GET_DATE%NOTFOUND;
END LOOP;
CLOSE GET_DATE; 
END;


SET SERVEROUTPUT ON
DECLARE
CURSOR GET_DATE
(INAGE Customs.price%TYPE)
IS
SELECT * FROM Product
WHERE price = INAGE;
a	GET_DATE%ROWTYPE;
BEGIN
OPEN GET_DATE(40); LOOP
DBMS_OUTPUT.enable;
DBMS_OUTPUT.put_line('Товары: '||a.id_producta||' '||a.product_name);
FETCH GET_DATE INTO a;
EXIT WHEN GET_DATE%NOTFOUND;
 END LOOP;
 CLOSE GET_DATE;
 END;

--#####################################################################################

SET SERVEROUTPUT ON 
DECLARE
CURSOR GET_PRODUCT
IS
SELECT * FROM "SUPPLYS", "ORDERS", "PRODUCTS"
WHERE (SUPPLYS.amount_product - ORDERS.amount_order <= 10000);
a GET_PRODUCT%ROWTYPE;
BEGIN
OPEN GET_PRODUCT; LOOP
DBMS_OUTPUT.enable;
DBMS_OUTPUT.put_line('остаток на конец месяца меньше 10000: '||a.full_name_product||' '|| a.id_product ||' '|| a.amount_product);
FETCH GET_PRODUCT INTO a; 
EXIT WHEN GET_PRODUCT%NOTFOUND;
END LOOP;
CLOSE GET_PRODUCT; 
END;

SET SERVEROUTPUT ON
DECLARE
CURSOR GET_DATE
(INAGE "POSTAVKA"."PRICE_TOVARA"%TYPE)
IS
SELECT * FROM "POSTAVKA"
WHERE "PRICE_TOVARA" = INAGE;
a	GET_DATE%ROWTYPE;
BEGIN
OPEN GET_DATE(50); LOOP
DBMS_OUTPUT.enable;
DBMS_OUTPUT.put_line('Товары: '||a.ID_TOV||' '||a.DATA_POSTAVKI);
FETCH GET_DATE INTO a;
EXIT WHEN GET_DATE%NOTFOUND;
 END LOOP;
 CLOSE GET_DATE;
 END;