CREATE OR REPLACE TRIGGER ADT2
AFTER INSERT OR DELETE OR UPDATE 
ON ZAKAZI
FOR EACH ROW 
DECLARE 
BEGIN 
INSERT INTO AUT (USER_NAME,TIME) VALUES (USER, SYSDATE); 
END; 

INSERT INTO ZAKAZI(ID_ZAKAZA,ID_YSLUGA,ID_ZAKAZCHIKA,DATE_ZAKAZA,KOL_VO_ZAKAZA) VALUES (10,3,2,TO_DATE('21.06.05','DD.MM.YY'),2); 

CREATE TABLE AUT (USER_NAME VARCHAR2(100),TIME DATE);






CREATE SEQUENCE AVTO1 START WITH 50 INCREMENT BY 33;

CREATE OR REPLACE TRIGGER IDENT
BEFORE INSERT ON "Customers"
FOR EACH ROW
DECLARE
BEGIN
SELECT AVTO.NEXTVAL
INTO :NEW.id_zakazchika
FROM DUAL;
END IDENT;

CREATE SEQUENCE AVTO2 START WITH 14 INCREMENT BY 6;

CREATE OR REPLACE TRIGGER IDENT
BEFORE INSERT ON "Customs"
FOR EACH ROW
DECLARE
BEGIN
SELECT AVTO.NEXTVAL
INTO :NEW.id_zakaza
FROM DUAL;
END IDENT;


CREATE SEQUENCE AVTO3 START WITH 20 INCREMENT BY 11;

CREATE OR REPLACE TRIGGER IDENT
BEFORE INSERT ON "Product"
FOR EACH ROW
DECLARE
BEGIN
SELECT AVTO.NEXTVAL
INTO :NEW.id_producta
FROM DUAL;
END IDENT;


SET SERVEROUTPUT ON DECLARE
CURSOR GET_DATE IS
SELECT * FROM Customs
WHERE id_producta = 2;
a	GET_DATE%ROWTYPE;
BEGIN
OPEN GET_DATE; LOOP
DBMS_OUTPUT.enable;
DBMS_OUTPUT.put_line('Заказы с id=2: '||a.custom_date||' '||a.done_or_not);
FETCH GET_DATE INTO a; 
EXIT WHEN GET_DATE%NOTFOUND;
END LOOP;
CLOSE GET_DATE; 
END;


SET SERVEROUTPUT ON
DECLARE
CURSOR GET_DATE
(INAGE Customs.price%TYPE)
IS
SELECT * FROM Product
WHERE price = INAGE;
a	GET_DATE%ROWTYPE;
BEGIN
OPEN GET_DATE(40); LOOP
DBMS_OUTPUT.enable;
DBMS_OUTPUT.put_line('Товары: '||a.id_producta||' '||a.product_name);
FETCH GET_DATE INTO a;
EXIT WHEN GET_DATE%NOTFOUND;
 END LOOP;
 CLOSE GET_DATE;
 END;