CREATE OR REPLACE TRIGGER ADT3
AFTER INSERT OR DELETE OR UPDATE 
ON TOVAR
FOR EACH ROW 
DECLARE 
BEGIN 
INSERT INTO AUT (USER_NAME,TIME) VALUES (USER, SYSDATE); 
END; 

INSERT INTO TOVAR(ID_TOV,NAZVANIE_TOVARA) VALUES ('2088228001','KOLBASAaaaaa');
CREATE TABLE AUT (USER_NAME VARCHAR2(100),TIME DATE);




CREATE SEQUENCE AVTO START WITH 20 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER IDENT
BEFORE INSERT ON "SUPPLYS"
FOR EACH ROW
DECLARE
BEGIN
SELECT AVTO.NEXTVAL
INTO : NEW.id_supply
FROM DUAL;
END IDENT;


CREATE SEQUENCE AVTO1 START WITH 50 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER IDENT
BEFORE INSERT ON "PRODUCERS"
FOR EACH ROW
DECLARE
BEGIN
SELECT AVTO.NEXTVAL
INTO :NEW.id_producer
FROM DUAL;
END IDENT;

CREATE SEQUENCE AVTO2 START WITH 14 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER IDENT
BEFORE INSERT ON "PRODUCTS"
FOR EACH ROW
DECLARE
BEGIN
SELECT AVTO.NEXTVAL
INTO :NEW.id_product
FROM DUAL;
END IDENT;


CREATE SEQUENCE AVTO3 START WITH 20 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER IDENT
BEFORE INSERT ON "ORDERS"
FOR EACH ROW
DECLARE
BEGIN
SELECT AVTO.NEXTVAL
INTO :NEW.id_order
FROM DUAL;
END IDENT;


CREATE SEQUENCE AVTO4 START WITH 20 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER IDENT
BEFORE INSERT ON "FACTORY"
FOR EACH ROW
DECLARE
BEGIN
SELECT AVTO.NEXTVAL
INTO :NEW.id_factory
FROM DUAL;
END IDENT;

CREATE SEQUENCE AVTO5 START WITH 20 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER IDENT
BEFORE INSERT ON "BUYER"
FOR EACH ROW
DECLARE
BEGIN
SELECT AVTO.NEXTVAL
INTO :NEW.id_buyer
FROM DUAL;
END IDENT;